markdown: kramdown
highlighter: rouge
permalink: "/:title"
url: LazsloBunz.github.io
baseurl: "/daddlyfe"
redcarpet:
  extensions:
  - strikethrough
  - tables
sass:
  sass_dir: public/css
  style: :compressed
title: dadd lyfe
github_username: LazsloBunz
theme: brume
